spring.application.name=musicapp

spring.datasource.url=jdbc:postgresql://localhost:5432/javalearn?characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'
